version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  mysql-zabbix:
    container_name: mysql-zabbix
    image: mysql:5.7
    networks:
      - network-zabbix
    volumes:
      - './zabbix/mysql:/var/lib/data'
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zabbix

  my-admin-zabbix:
    image: phpmyadmin/phpmyadmin
    networks:
      - network-zabbix
    container_name: my-admin-zabbix
    links:
      - mysql-zabbix
    environment:
      PMA_HOST: mysql-zabbix
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8083:80

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql-zabbix
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      - DB_SERVER_HOST=mysql-zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=root
    depends_on:
      - mysql-zabbix

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    networks:
      - network-zabbix
    links:
      - mysql-zabbix
    restart: always
    ports:
      - '8082:8080'
      - '443:8443'
    environment:
      - DB_SERVER_HOST=mysql-zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=root
      - PHP_TZ=America/Sao_Paulo
    depends_on:
      - mysql-zabbix
   
  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - network-zabbix
    links:
      - mysql-zabbix
      - zabbix-server
    restart: always
    ports:
      - '3000:3000'
    environment: 
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql-zabbix
      - zabbix-server
  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-5.0.1
    user: root
    networks:
      - network-zabbix
    links:
      - zabbix-server
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=172.18.0.1

  front:
    image: kkaaee1990/front-nginx:latest
    container_name: front-end
    ports:
      - "8080:80"
    restart: always
    
  back:
    container_name: back-end
    build: back/
    volumes:
      - ./back:/python/src

  mysql: 
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
    volumes:
      - "./mysql:/var/lib/mysql"

  my-admin:
    image: phpmyadmin/phpmyadmin
    container_name: my-admin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    